==================================== Data Analysis ========================================
1. Pandas     : Data frame analysis 
2. numpy      : numerical analysis
3. matplotlib : graphs and plots
4. seaborn    : plots
5. bokhe      : plots
6. plotly     : plots

==================================  Machine Learning  ==========================================
7. Stats                  : for statistical models
8. Scikit-learn(sk learn) : ML models

==================================== Deep Learning =============================================
9. opencv          : computer vision
10. pillow         : image operations
11. tensorflow     : Neural Network Creation
12. keras          : NN
13. pytorch        : alternative package of tensorflow (facebook meta)

================================== NLP ===========================================================
14. NLTK           : Natural language toolkit
15. SpacV          : Alternative To NLTK
16. wordcloud      : most frequent occured words

================================ Scrapping ======================================================
17. SqLIte          : Database Creation
18. Beautiful soup  : 
19. selenium


================================ API Creation =====================================================
20. Flask
21. FastAPI
22. Gradio
23. Django

================================== UI app Creation ===================================================
24. Stramlit

==================================== Transfer Learning Models(DL) ================================================

25. MobileNet
26. Resnet
27. VGGnet
28. Iception
29. Yolo            :  Ultralytics


====================================== Transfer Learning Models(NLP) ==============================================
30. Word2vec
31. Glove

======================================== Huging Face Transformation ===============================================
32. BERT    : Bi directional Encoder representation of transformer

====================================== Allen NLP ==============================
33. Allen NLP packages

====================================== GenAI =============================
34. LAngChain
35. Google Gemin ai related package
36. Open Ai GPT related packages
37. Amazon BedRock related packages
38. Meta Llama related packges

==================================== Image and Audio Generation ==========================
39. GAN models related packages
40. SORA related packages

================================== Model Deployement(MLOps) ======================
41. mlflow using datbricks
42. kubeflow (GCP account)

======================================== Cloud Aplications =====================
43. Azure ML related packages
44. GCP VertexAI related packages
45. AWS segamaker related packages
    
================================ Small ==============================
46. time
47. logging
48. math
49. random
50. Env
51. OS

****step:-1 : import packages****

In [90]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

**Step 2: Create A Data Frame Using List**


- data : your data in either list format or dict format

- index  : we need to provide a list

- columns : we need to provide a list

In [92]:
names=['ramesh', 'suresh', 'satish']
pd.DataFrame(names, index=['a','b','c'],
             columns=['Names'])
# pd.DataFrame(data,index,columns)

    Names
a  ramesh
b  suresh
c  satish

**Step 3:**

In [98]:
names=['ramesh', 'suresh', 'satish']
idx=['a', 'b', 'c']
cols = ['names']
pd.DataFrame(names,columns=cols,index=idx)

    names
a  ramesh
b  suresh
c  satish

In [100]:
names = ['Ramesh', 'Suresh', 'Ganesh']
ages = [20,22,25]
pd.DataFrame(zip(names, ages), 
            columns= ['Names', 'Age'])

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Ganesh   25

In [103]:
names = ['Ramesh', 'Suresh', 'Ganesh']
ages = [20,22,25]
pd.DataFrame(zip(names, ages), 
            columns= ['Names', 'Age'])

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Ganesh   25

**Step 5: Create empty Data and update the columns**

In [105]:
df=pd.DataFrame()
df['Names']=['Ramesh', 'Suresh', 'Ganesh']
df['Age']=[22, 25 , 36]
df

    Names  Age
0  Ramesh   22
1  Suresh   25
2  Ganesh   36

**Step 6: Add a New column with existing dataframe**

In [108]:
names = ['Ramesh', 'Suresh', 'Ganesh']
ages = [20,22,25]
pd.DataFrame(zip(names, ages), 
            columns= ['Names', 'Age'])

df['city']=['hyd', 'mum', 'jal']
df

    Names  Age city
0  Ramesh   22  hyd
1  Suresh   25  mum
2  Ganesh   36  jal

**Step 7: overwrite the column values**

- i want to overwrite my age values

- originally age is [20,22,24]

- now i want to update the age = [30,32,34]

In [111]:
df['Age'] = [30, 32, 34]
df

    Names  Age city
0  Ramesh   30  hyd
1  Suresh   32  mum
2  Ganesh   34  jal

In [113]:
# case sensitive
df['age'] = [30, 32, 34]
df

    Names  Age city  age
0  Ramesh   30  hyd   30
1  Suresh   32  mum   32
2  Ganesh   34  jal   34

**Step 8: Drop the column**

- labels

- axis

- index

- columns

- inplace

In [116]:
df.drop('age') # error
df.drop('age', axis=0) # error because axis = 0 is used for index
df.drop('age', axis=1)  # right bcz axis = 1 is used for columns
# by default axis = 0

KeyError: "['age'] not found in axis"

In [123]:
df.drop(2)

    Names  Age city  age
0  Ramesh   30  hyd   30
1  Suresh   32  mum   32

In [125]:
df.drop(columns=['age'])
df

    Names  Age city  age
0  Ramesh   30  hyd   30
1  Suresh   32  mum   32
2  Ganesh   34  jal   34

In [127]:
df.drop(columns='age',inplace=True)
df

    Names  Age city
0  Ramesh   30  hyd
1  Suresh   32  mum
2  Ganesh   34  jal

In [129]:
df.drop('age',axis=1)

KeyError: "['age'] not found in axis"

In [131]:
df.drop(index=2,axis=0)

    Names  Age city
0  Ramesh   30  hyd
1  Suresh   32  mum

In [133]:
df.drop(2, axis=0)

    Names  Age city
0  Ramesh   30  hyd
1  Suresh   32  mum

In [135]:
df.drop(index=2)

    Names  Age city
0  Ramesh   30  hyd
1  Suresh   32  mum

In [137]:
df

    Names  Age city
0  Ramesh   30  hyd
1  Suresh   32  mum
2  Ganesh   34  jal

In [139]:
df.drop(labels=2)

    Names  Age city
0  Ramesh   30  hyd
1  Suresh   32  mum

In [141]:
df.drop()

ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

In [143]:
import pandas as pd
names = ['Ramesh', 'Suresh', 'Ganesh']
ages = [20,22,25]
salary = [120000, 254000, 650000]
df1 = pd.DataFrame(zip(names, ages, salary), 
            columns = ['Names', 'Age', 'Salary'])
df1

    Names  Age  Salary
0  Ramesh   20  120000
1  Suresh   22  254000
2  Ganesh   25  650000

In [145]:
df1.drop(labels=2)

    Names  Age  Salary
0  Ramesh   20  120000
1  Suresh   22  254000

In [147]:
names = ['ramesh', 'suresh', 'kamlesh']
pd.DataFrame(names, columns=['Names'])

     Names
0   ramesh
1   suresh
2  kamlesh

In [149]:
av=pd.DataFrame()
av['names']=['ram', 'shyam', 'ghanashyam','raj','vaibhav','sahil']
av
av.index={65,66,67,68,69,70}
av['city']=['hyd', 'mum', 'pune','akola','jal','jam']
av['marks']=[85,89,68,65,48,98]
av['rank']=[3,2,4,5,6,1]
av

         names   city  marks  rank
65         ram    hyd     85     3
66       shyam    mum     89     2
67  ghanashyam   pune     68     4
68         raj  akola     65     5
69     vaibhav    jal     48     6
70       sahil    jam     98     1

In [151]:
av[['names','marks']]

         names  marks
65         ram     85
66       shyam     89
67  ghanashyam     68
68         raj     65
69     vaibhav     48
70       sahil     98

In [153]:
av.iloc([1,1])

TypeError: unhashable type: 'list'

In [155]:
av.loc[:1,'names']

Series([], Name: names, dtype: object)

In [157]:
import pandas as pd
students={'Name': ['Raj', 'Rohit', 'Ram'],
           'Age': [19,21,20],
        'Marks' :[88,90,94]}
ab=pd.DataFrame(students)
ab

    Name  Age  Marks
0    Raj   19     88
1  Rohit   21     90
2    Ram   20     94

In [159]:
ab.iloc(0, 2)

TypeError: _LocationIndexer.__call__() takes from 1 to 2 positional arguments but 3 were given

In [161]:
ab.head(2)

    Name  Age  Marks
0    Raj   19     88
1  Rohit   21     90

In [163]:
ab['Roll Number'] = [1,2,3]
ab.index=[1,2,3]
print(ab)

    Name  Age  Marks  Roll Number
1    Raj   19     88            1
2  Rohit   21     90            2
3    Ram   20     94            3

In [165]:
ab.tail(2)

    Name  Age  Marks  Roll Number
2  Rohit   21     90            2
3    Ram   20     94            3

In [167]:
ab.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 1 to 3
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         3 non-null      object
 1   Age          3 non-null      int64
 2   Marks        3 non-null      int64
 3   Roll Number  3 non-null      int64
dtypes: int64(3), object(1)
memory usage: 120.0+ bytes

In [169]:
ab.describe()

        Age      Marks  Roll Number
count   3.0   3.000000          3.0
mean   20.0  90.666667          2.0
std     1.0   3.055050          1.0
min    19.0  88.000000          1.0
25%    19.5  89.000000          1.5
50%    20.0  90.000000          2.0
75%    20.5  92.000000          2.5
max    21.0  94.000000          3.0

In [171]:
# Filtering Operations
ab[ab['Marks']>85]   #Condition
ab[(ab['Marks']>80) & (ab['Age']>20)] # multiple conditions

    Name  Age  Marks  Roll Number
2  Rohit   21     90            2

In [173]:
ab

    Name  Age  Marks  Roll Number
1    Raj   19     88            1
2  Rohit   21     90            2
3    Ram   20     94            3

In [175]:
# Updating Column values
ab['Marks']=ab['Marks']-1
ab['Age']=ab['Age']+1
ab
ab['Home town']=['mum', 'jal', 'pune']
ab

    Name  Age  Marks  Roll Number Home town
1    Raj   20     87            1       mum
2  Rohit   22     89            2       jal
3    Ram   21     93            3      pune

In [177]:
# for deleting rows and columns use "drop" method 
ab.drop('Roll Number',axis=1)
ab.drop(1) # automatically deletes the index given, because default axis=0
ab.drop('Home town', axis=1, inplace=True) # by using inplace = True we permenantly delete the column
ab

    Name  Age  Marks  Roll Number
1    Raj   20     87            1
2  Rohit   22     89            2
3    Ram   21     93            3

In [179]:
ab

    Name  Age  Marks  Roll Number
1    Raj   20     87            1
2  Rohit   22     89            2
3    Ram   21     93            3

In [181]:
# used for sorting the data 
ab.sort_values(by='Age')
ab.sort_values(by='Marks')

    Name  Age  Marks  Roll Number
1    Raj   20     87            1
2  Rohit   22     89            2
3    Ram   21     93            3

In [183]:
# df.at method is good for replacing a single value 
ab.at[1, 'Marks']=90
ab

    Name  Age  Marks  Roll Number
1    Raj   20     90            1
2  Rohit   22     89            2
3    Ram   21     93            3

In [185]:
#df.loc is very flexible method and can be used for changing/replacing multiple values
ab.loc[[1,2], 'Marks']=[85, 75]
ab

    Name  Age  Marks  Roll Number
1    Raj   20     85            1
2  Rohit   22     75            2
3    Ram   21     93            3

In [187]:
# agregations
av['Marks'].mean()
av['Marks'].min()
av['Marks'].sum()
av['Marks'].max()

KeyError: 'Marks'

**Step 9: Rename the columns**

In [190]:
ab

    Name  Age  Marks  Roll Number
1    Raj   20     85            1
2  Rohit   22     75            2
3    Ram   21     93            3

In [192]:
av

         names   city  marks  rank
65         ram    hyd     85     3
66       shyam    mum     89     2
67  ghanashyam   pune     68     4
68         raj  akola     65     5
69     vaibhav    jal     48     6
70       sahil    jam     98     1

In [194]:
av.rename()

TypeError: must pass an index to rename

In [196]:
mapper: is dictionary

SyntaxError: invalid syntax (1162521000.py, line 1)

In [198]:
dict1= {'Age' : 'age'}
av.rename(columns = dict1)

         names   city  marks  rank
65         ram    hyd     85     3
66       shyam    mum     89     2
67  ghanashyam   pune     68     4
68         raj  akola     65     5
69     vaibhav    jal     48     6
70       sahil    jam     98     1

In [200]:
dict1= {'Age' : 'age'}
av.rename(columns = dict1, inplace=True)
av

         names   city  marks  rank
65         ram    hyd     85     3
66       shyam    mum     89     2
67  ghanashyam   pune     68     4
68         raj  akola     65     5
69     vaibhav    jal     48     6
70       sahil    jam     98     1

In [202]:
dict1= {'age' : 'Age'}
av.rename(columns = dict1, inplace=True)
av

         names   city  marks  rank
65         ram    hyd     85     3
66       shyam    mum     89     2
67  ghanashyam   pune     68     4
68         raj  akola     65     5
69     vaibhav    jal     48     6
70       sahil    jam     98     1

In [204]:
dict1= {'age' : 'Age'}
av.rename(dict1, axis=1 )
av

         names   city  marks  rank
65         ram    hyd     85     3
66       shyam    mum     89     2
67  ghanashyam   pune     68     4
68         raj  akola     65     5
69     vaibhav    jal     48     6
70       sahil    jam     98     1

In [206]:
dict1= {'Age' : 'age'}
av.rename(columns = dict1, inplace=True)
av

         names   city  marks  rank
65         ram    hyd     85     3
66       shyam    mum     89     2
67  ghanashyam   pune     68     4
68         raj  akola     65     5
69     vaibhav    jal     48     6
70       sahil    jam     98     1

In [208]:
dict1= {'Name' : 'name'}
av.rename(columns = dict1, inplace=True)
av

         names   city  marks  rank
65         ram    hyd     85     3
66       shyam    mum     89     2
67  ghanashyam   pune     68     4
68         raj  akola     65     5
69     vaibhav    jal     48     6
70       sahil    jam     98     1

In [210]:
dict1= {'marks' : 'Marks', 'age': 'Age', 'names': 'Name'}
av.rename(columns = dict1, inplace=True)
av

          Name   city  Marks  rank
65         ram    hyd     85     3
66       shyam    mum     89     2
67  ghanashyam   pune     68     4
68         raj  akola     65     5
69     vaibhav    jal     48     6
70       sahil    jam     98     1

In [309]:
av.loc[65:68,['Name','city']]

          Name   city
65         ram    hyd
66       shyam    mum
67  ghanashyam   pune
68         raj  akola

In [311]:
av.loc[[65,68],['Name','city']]

   Name   city
65  ram    hyd
68  raj  akola

In [212]:
dict_1={2:'B'}
ab.rename(index=dict_1, inplace=True)
ab

    Name  Age  Marks  Roll Number
1    Raj   20     85            1
B  Rohit   22     75            2
3    Ram   21     93            3

In [214]:
dict_1={3:'C'}
ab.rename(dict_1)

    Name  Age  Marks  Roll Number
1    Raj   20     85            1
B  Rohit   22     75            2
C    Ram   21     93            3

In [216]:
import pandas as pd
df0=pd.DataFrame()
df0['n2']= [i for i in range(1,15)]
df0['square_value'] = [i**2 for i in range(1,15)]
df0

    n2  square_value
0    1             1
1    2             4
2    3             9
3    4            16
4    5            25
5    6            36
6    7            49
7    8            64
8    9            81
9   10           100
10  11           121
11  12           144
12  13           169
13  14           196

In [218]:
df1=pd.DataFrame()
df1['n1']= [i for i in range(1,10)]
df1['sq_value']=[i**2 for i in range(1,10)]
df1['cube_value']=[i**3 for i in range(1,10)]
df1

   n1  sq_value  cube_value
0   1         1           1
1   2         4           8
2   3         9          27
3   4        16          64
4   5        25         125
5   6        36         216
6   7        49         343
7   8        64         512
8   9        81         729

In [220]:
df1.loc[df1['cube_value']==27, 'cube_value']=100
df1
df1.loc[2, 'cube_value']=101
df1

   n1  sq_value  cube_value
0   1         1           1
1   2         4           8
2   3         9         101
3   4        16          64
4   5        25         125
5   6        36         216
6   7        49         343
7   8        64         512
8   9        81         729

In [295]:
df1.at[2, 'cube_value']=102
df1.iat[0,2]=100
df1

   n1  sq_value  cube_value
0   1         1         100
1   2         4         101
2   3         9         102
3   4        16          64
4   5        25         125
5   6        36         216
6   7        49         343
7   8        64         512
8   9        81         729

In [224]:
df1.drop('cube_value', axis = 1)

   n1  sq_value
0   1         1
1   2         4
2   3         9
3   4        16
4   5        25
5   6        36
6   7        49
7   8        64
8   9        81

In [226]:
df1

   n1  sq_value  cube_value
0   1         1           1
1   2         4           8
2   3         9         102
3   4        16          64
4   5        25         125
5   6        36         216
6   7        49         343
7   8        64         512
8   9        81         729

- len 

- columns 

- shape

- dtypes

- head

- tail

In [229]:
df1.shape

(9, 3)

In [231]:
df1.columns

Index(['n1', 'sq_value', 'cube_value'], dtype='object')

In [233]:
df1.dtypes

n1            int64
sq_value      int64
cube_value    int64
dtype: object

In [235]:
df1.head()

   n1  sq_value  cube_value
0   1         1           1
1   2         4           8
2   3         9         102
3   4        16          64
4   5        25         125

In [237]:
df1.tail()

   n1  sq_value  cube_value
4   5        25         125
5   6        36         216
6   7        49         343
7   8        64         512
8   9        81         729

In [239]:
len(df1)

9

In [241]:
df1.columns

Index(['n1', 'sq_value', 'cube_value'], dtype='object')

In [243]:
list(df1.columns)

['n1', 'sq_value', 'cube_value']

In [245]:
df1.columns.to_list()

['n1', 'sq_value', 'cube_value']

In [247]:
df1.dtypes
#int : int 
#float : float
#string : object

n1            int64
sq_value      int64
cube_value    int64
dtype: object

In [249]:
df1.isnull()
# we are asking a question
# a null value available or not
# True or False
# True means yes NULL available 
# false mean there no Null

      n1  sq_value  cube_value
0  False     False       False
1  False     False       False
2  False     False       False
3  False     False       False
4  False     False       False
5  False     False       False
6  False     False       False
7  False     False       False
8  False     False       False

In [251]:
df1.isnull().sum()
# column wise null value will display

n1            0
sq_value      0
cube_value    0
dtype: int64

In [253]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   n1          9 non-null      int64
 1   sq_value    9 non-null      int64
 2   cube_value  9 non-null      int64
dtypes: int64(3)
memory usage: 348.0 bytes

**Step-10: How to change a specific value of a column**

- df1.drop

        - either it will drop column or index

- df1.rename

In [256]:
df1

   n1  sq_value  cube_value
0   1         1           1
1   2         4           8
2   3         9         102
3   4        16          64
4   5        25         125
5   6        36         216
6   7        49         343
7   8        64         512
8   9        81         729

In [258]:
dict_2 ={64: 464, 1:111}
df1.replace( dict_2,) # all data  will be replaced

    n1  sq_value  cube_value
0  111       111         111
1    2         4           8
2    3         9         102
3    4        16         464
4    5        25         125
5    6        36         216
6    7        49         343
7    8       464         512
8    9        81         729

**Step-11: Selection of a column**

In [261]:
type(df1['cube_value'])
# series 
# series looks like data frame
# no row and column

pandas.core.series.Series

In [263]:
df1.shape

(9, 3)

In [265]:
df1['cube_value'].shape

(9,)

In [267]:
df1[['cube_value']].shape

(9, 1)

In [269]:
df1['cube_value'].shape
# 1D data

(9,)

In [271]:
# sq_value
# cube _value
# to print multiple columns always use/keep them in list 
df1[['sq_value', 'cube_value']]  # never use single sq brackets theese
# df1[['cube_value','sq_value']]

   sq_value  cube_value
0         1           1
1         4           8
2         9         102
3        16          64
4        25         125
5        36         216
6        49         343
7        64         512
8        81         729

<!-- -
create a dataFrame
add columns
delete column
repace column name
replace column value -->

In [339]:
x=df1['sq_value']
x.replace(81,144,  inplace = True)
df1

   n1  sq_value  cube_value
0   1         1         100
1   2         4         101
2   3         9         102
3   4        16          64
4   5        25         125
5   6        36         216
6   7        49         343
7   8        64         512
8   9       144         729

In [355]:

df1['sq_value'].replace(1,144,  inplace = True)
df1

   n1  sq_value  cube_value
0   1       144         100
1   2        14         101
2   3         9         102
3   4        16          64
4   5        25         125
5   6        36         216
6   7        49         343
7   8        14         512
8   9       144         729

In [351]:
x=df1['sq_value']
x.replace({64:14},  inplace = True)
df1

   n1  sq_value  cube_value
0   1         1         100
1   2         4         101
2   3         9         102
3   4        16          64
4   5        25         125
5   6        36         216
6   7        49         343
7   8        14         512
8   9       144         729

In [353]:
df1['sq_value'].replace({4:14},  inplace = True)
df1

   n1  sq_value  cube_value
0   1         1         100
1   2        14         101
2   3         9         102
3   4        16          64
4   5        25         125
5   6        36         216
6   7        49         343
7   8        14         512
8   9       144         729

In [280]:
df1.replace({64:464, 1:111})

    n1  sq_value  cube_value
0  111       111         111
1    2         4           8
2    3         9         102
3    4        16         464
4    5        25         125
5    6        36         216
6    7        49         343
7    8       464         512
8    9        81         729