In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [7]:
import pandas as pd
name=['Sameer','Shyam', 'Rohan', 'Rajendra']
marks = [81, 68, 96, 89]
roll_no = [1, 2, 3, 4]
subject = ['math', 'Science', 'Math', 'Physics']
info = {'Roll_no':roll_no,
        'Name': name,
        'Subject': subject,
        'Marks' : marks
       }
std = pd.DataFrame(info, )
std

   Roll_no      Name  Subject  Marks
0        1    Sameer     math     81
1        2     Shyam  Science     68
2        3     Rohan     Math     96
3        4  Rajendra  Physics     89

In [9]:
import pandas as pd
name=['Sameer','Shyam', 'Rohan', 'Rajendra']
marks = [81, 68, 96, 89]
roll_no = [1, 2, 3, 4]
subject = ['math', 'Science', 'Math', 'Physics']
info = {'Roll_no':roll_no,
        'Name': name,
        'Subject': subject,
        'Marks' :[81, 70, 96, 89]
       }
std = pd.DataFrame(info, index = roll_no)
std

   Roll_no      Name  Subject  Marks
1        1    Sameer     math     81
2        2     Shyam  Science     70
3        3     Rohan     Math     96
4        4  Rajendra  Physics     89

In [ ]:
help(pd.DataFrame())

In [49]:
students_data = {'Roll_num':[1, 2, 3, 4, 5],
                 'Name': ['Atul', 'Himanshu', 'Pranav', 'Bhagat', 'Bharat'],
                 'Subject' : ['Math', 'Physics', 'Chemistry', 'Marathi', 'English'],
                 'Marks' : [58,89,65,87,78],
                 'City' : ['Jalgaon', 'Jamner', 'Pusad', 'Kandari', 'Zts' ]               
                }
std_d = pd.DataFrame(students_data)
std_d

   Roll_num      Name    Subject  Marks     City
0         1      Atul       Math     58  Jalgaon
1         2  Himanshu    Physics     89   Jamner
2         3    Pranav  Chemistry     65    Pusad
3         4    Bhagat    Marathi     87  Kandari
4         5    Bharat    English     78      Zts

In [245]:
std_d[['Name', 'Marks']] # always use double brackets to print two columns beacause its a 2d data and single bracket represents only 1d data

       Name  Marks
0      Atul     58
1  Himanshu     89
2    Pranav     65
3    Bhagat     87
4    Bharat     78
5   Vaibhav     86

In [13]:
std_d[['Name', 'Marks', 'Subject']]

       Name  Marks    Subject
0      Atul     58       Math
1  Himanshu     89    Physics
2    Pranav     65  Chemistry
3    Bhagat     87    Marathi
4    Bharat     78    English

In [13]:
std_d['Marks'][2]

65

**Different Operations on DataFrame**
- a DataFrame for example std_d
- To acess only specific columns std_d[[column, names]] always use double [[]]
- [] it gives output as series not a dataframe. because series is 1d and dataframe is 2d so we should always use double sq bracktes
- you can access multiple columns

- you can also access a specific data point from a column ex : std_d['Marks'][2] you marks of 2 index student

- std_d['Name'][3],  '---------->' ,std_d['Marks'][4]

- You can replace data by using std_d.replace(['chemistry', 'Biology']) But it rplaces all the values with the given value

- so for replacing a specific value you should use loc : std_d.loc[2, 'Marks;]='Psychology' (rows, columns) : you can put index of row but can not put index of column. you can use iloc for that purpose

- you can insert a row using loc but you can not insert a row using iloc : std_d['Grade']=['CD', 'AB', 'BC', 'AB', 'BB']

-

In [255]:
std_d['Name'][3],  '---------->' ,std_d['Marks'][4]

('Bhagat', '---------->', 78)

In [17]:
std_d.replace('Chemistry', 'Biology')

   Roll_num      Name  Subject  Marks     City
0         1      Atul     Math     58  Jalgaon
1         2  Himanshu  Physics     89   Jamner
2         3    Pranav  Biology     65    Pusad
3         4    Bhagat  Marathi     87  Kandari
4         5    Bharat  English     78      Zts

In [27]:
std_d.replace(['Jalgaon', 'Jamner', 'Kandari', 'Pusad', 'Zts'],'Bhusawal') # used for replacing multiple values with one value

   Roll_num      Name    Subject  Marks      City
0         1      Atul       Math     58  Bhusawal
1         2  Himanshu    Physics     89  Bhusawal
2         3    Pranav  Chemistry     65  Bhusawal
3         4    Bhagat    Marathi     87  Bhusawal
4         5    Bharat    English     78  Bhusawal

In [29]:
std_d

   Roll_num      Name    Subject  Marks     City
0         1      Atul       Math     58  Jalgaon
1         2  Himanshu    Physics     89   Jamner
2         3    Pranav  Chemistry     65    Pusad
3         4    Bhagat    Marathi     87  Kandari
4         5    Bharat    English     78      Zts

In [33]:
std_d.loc[2, 'Subject']='Psychology'
std_d
#std_d.drop('Subjetct', axis=1)

   Roll_num      Name     Subject  Marks     City Grade
0         1      Atul        Math     58  Jalgaon    CD
1         2  Himanshu     Physics     89   Jamner    AB
2         3    Pranav  Psychology     65    Pusad    BC
3         4    Bhagat     Marathi     87  Kandari    AB
4         5    Bharat     English     78      Zts    BB

In [25]:
std_d['Grade']=['CD', 'AB', 'BC', 'AB', 'BB']

In [35]:
std_d

   Roll_num      Name    Subject  Marks     City
0         1      Atul       Math     58  Jalgaon
1         2  Himanshu    Physics     89   Jamner
2         3    Pranav  Chemistry     65    Pusad
3         4    Bhagat    Marathi     87  Kandari
4         5    Bharat    English     78      Zts

In [37]:
std_d.replace({'Math' : 'AB', 'Physics': 'AA'}) # replace multiple values with the help of dictionary

   Roll_num      Name    Subject  Marks     City
0         1      Atul         AB     58  Jalgaon
1         2  Himanshu         AA     89   Jamner
2         3    Pranav  Chemistry     65    Pusad
3         4    Bhagat    Marathi     87  Kandari
4         5    Bharat    English     78      Zts

In [55]:
std_d['Subject'] = std_d['Subject'].replace({'Math' : 'Algebra', 'Biology': 'Zoology'})
std_d

   Roll_num      Name    Subject  Marks     City
0         1      Atul    Algebra     58  Jalgaon
1         2  Himanshu    Zoology     89   Jamner
2         3    Pranav  Chemistry     65    Pusad
3         4    Bhagat    Marathi     87  Kandari
4         5    Bharat    English     78      Zts

In [61]:
std_d.drop()

   Roll_num      Name  Subject  Marks     City
0         1      Atul  Algebra     58  Jalgaon
1         2  Himanshu  Zoology     89   Jamner
3         4    Bhagat  Marathi     87  Kandari
4         5    Bharat  English     78      Zts

In [65]:
num = pd.DataFrame()
num['n1'] = [i for i in range(1,10)]
num['sq'] = [i**2 for i in range(1,10)]
num['cube'] = [i**3  for i in range(1,10)]
num

   n1  sq  cube
0   1   1     1
1   2   4     8
2   3   9    27
3   4  16    64
4   5  25   125
5   6  36   216
6   7  49   343
7   8  64   512
8   9  81   729

In [31]:
num['cube']=num['cube'].mask(num['cube']>300, 0)
num

   n1  sq  cube
0   1   1     1
1   2   4     8
2   3   9    27
3   4  16    64
4   5  25   125
5   6  36   216
6   7  49     0
7   8  64     0
8   9  81     0

In [99]:
num['cube'] = num['cube'].mask(num['cube']==343,5)
num.sort_values(by ='cube')

   n1  sq  cube
0   1   1     1
6   7  49     5
1   2   4     8
2   3   9    27
3   4  16    64
4   5  25   125
5   6  36   216
7   8  64   512
8   9  81   729

In [81]:
cond= num.sort_values(by = 'cube', ascending = False)
cond

   n1  sq  cube
8   9  81   729
7   8  64   512
6   7  49   343
5   6  36   216
4   5  25   125
3   4  16    64
2   3   9    27
1   2   4     8
0   1   1     1

In [77]:
num

   n1  sq  cube
0   1   1     1
1   2   4     8
2   3   9    27
3   4  16    64
4   5  25   125
5   6  36   216
6   7  49   343
7   8  64   512
8   9  81   729

In [257]:
std_d.sort_values(by='Marks', ascending=False)
#std_d.drop('Subjetct', axis = True, inplace=True,)

   Roll_num      Name    Subject  Marks     City
1         2  Himanshu    Physics     89   Jamner
3         4    Bhagat    Marathi     87  Kandari
4         5    Bharat    English     78      Zts
2         3    Pranav  Chemistry     65    Pusad
0         1      Atul       Math     58  Jalgaon

In [133]:
std_d

   Roll_num      Name  Subject  Marks     City Grade
0         1      Atul     Math     58  Jalgaon    CD
1         2  Himanshu  Physics     89   Jamner    AB
2         3    Pranav  Biology     65    Pusad    BC
3         4    Bhagat  Marathi     87  Kandari    AB
4         5    Bharat  English     78      Zts    BB

In [101]:
std_d

   Roll_num      Name    Subject  Marks     City
0         1      Atul    Algebra     58  Jalgaon
1         2  Himanshu    Zoology     89   Jamner
2         3    Pranav  Chemistry     65    Pusad
3         4    Bhagat    Marathi     87  Kandari
4         5    Bharat    English     78      Zts

In [105]:
n_s = {'Roll_num': [6],
       'Name' : ['Vaibhav'],
       'Subject' : ['Python'],
       'Marks' : [86], 
       'City' : ['Jamner'],
       'Grade' : ['AB']}
ns1=pd.DataFrame(n_s)
ns1

   Roll_num     Name Subject  Marks    City Grade
0         6  Vaibhav  Python     86  Jamner    AB

In [107]:
std_d+ns1

            City  Grade  Marks         Name  Roll_num        Subject
0  JalgaonJamner    NaN  144.0  AtulVaibhav       7.0  AlgebraPython
1            NaN    NaN    NaN          NaN       NaN            NaN
2            NaN    NaN    NaN          NaN       NaN            NaN
3            NaN    NaN    NaN          NaN       NaN            NaN
4            NaN    NaN    NaN          NaN       NaN            NaN

In [109]:
std_d

   Roll_num      Name    Subject  Marks     City
0         1      Atul    Algebra     58  Jalgaon
1         2  Himanshu    Zoology     89   Jamner
2         3    Pranav  Chemistry     65    Pusad
3         4    Bhagat    Marathi     87  Kandari
4         5    Bharat    English     78      Zts

In [111]:
std_d=pd.concat([std_d, ns1],) # used for adding two data frames
std_d

   Roll_num      Name    Subject  Marks     City Grade
0         1      Atul    Algebra     58  Jalgaon   NaN
1         2  Himanshu    Zoology     89   Jamner   NaN
2         3    Pranav  Chemistry     65    Pusad   NaN
3         4    Bhagat    Marathi     87  Kandari   NaN
4         5    Bharat    English     78      Zts   NaN
0         6   Vaibhav     Python     86   Jamner    AB

In [113]:
std_d=std_d.reset_index() # used for resenting the index

In [219]:
std_d

   level_0  index  Roll_num      Name  Subject  Marks     City Grade
0        0      0         1      Atul     Math     58  Jalgaon    CD
1        1      1         2  Himanshu  Physics     89   Jamner    AB
2        2      2         3    Pranav  Biology     65    Pusad    BC
3        3      3         4    Bhagat  Marathi     87  Kandari    AB
4        4      4         5    Bharat  English     78      Zts    BB
5        5      0         6   Vaibhav   Python     86   Jamner    AB
6        6      0         6   Vaibhav   Python     86   Jamner    AB

In [ ]:

std_d = std_d.drop(columns=['level_0', 'index'])

In [ ]:
std_d=std_d.drop(['level_0', 'index'], axis=1) # used to delete or drop the extra index. When there are more than one index they are saved by the name
# of level_0 and index

In [121]:
std_d.drop(5, inplace=True)

In [131]:
std_d.drop(columns = 'index', inplace = True)

In [133]:
std_d

   Roll_num      Name    Subject  Marks     City Grade
0         1      Atul    Algebra     58  Jalgaon   NaN
1         2  Himanshu    Zoology     89   Jamner   NaN
2         3    Pranav  Chemistry     65    Pusad   NaN
3         4    Bhagat    Marathi     87  Kandari   NaN
4         5    Bharat    English     78      Zts   NaN

In [135]:
std_d.drop(std_d[std_d['Marks']<80].index) # used for filtering by conditions

   Roll_num      Name  Subject  Marks     City Grade
1         2  Himanshu  Zoology     89   Jamner   NaN
3         4    Bhagat  Marathi     87  Kandari   NaN

In [259]:
num

   n1  sq  cube
0   1   1     1
1   2   4     8
2   3   9    27
3   4  16    64
4   5  25   125
5   6  36   216
6   7  49     0
7   8  64     0
8   9  81     0

In [65]:
num['cube'].replace(64,464)

0      1
1      8
2     27
3    464
4    125
5    216
6      0
7      0
8      0
Name: cube, dtype: int64

**Step 12: How to add / append a row**



- we will use loc

In [146]:
num.loc[1:3, 1:2] # we can not insert the index number of columns in loc we have to provide the names of the column instead

TypeError: cannot do slice indexing on Index with these indexers [1] of type int

In [148]:
num.iloc[1:6, 1:3] # in iloc we can directly put index of columns unlike loc
# i in iloc stands for index

   sq  cube
1   4     8
2   9    27
3  16    64
4  25   125
5  36   216

In [270]:
num.loc[1:6, ['sq', 'cube']]

   sq  cube
1   4     8
2   9    27
3  16   464
4  25   125
5  36   216
6  49     0

In [274]:
cols= ['sq', 'cube']
num.loc[1:6,cols] # loc doent take index of columns so we have to provide name of the columns

   sq  cube
1   4     8
2   9    27
3  16   464
4  25   125
5  36   216
6  49     0

In [300]:
num.iloc[[2,3,4]]

   n1  sq  cube
2   3   9    27
3   4  16   464
4   5  25   125

In [278]:
num.iloc[[2]]

   n1  sq  cube
2   3   9    27

In [280]:
num.iloc[2]

n1       3
sq       9
cube    27
Name: 2, dtype: int64

In [304]:
num.iloc[[2,3,4],[0,2]]

   n1  cube
2   3    27
3   4   464
4   5   125

In [284]:
num.iloc[2,0]

3

In [152]:
num.iloc[:,0]

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: n1, dtype: int64

In [310]:
num.iloc[2,:]

n1       3
sq       9
cube    27
Name: 2, dtype: int64

In [294]:
num.iloc[[2],:]

   n1  sq  cube
2   3   9    27

In [296]:
num.iloc[2:6,0]

2    3
3    4
4    5
5    6
Name: n1, dtype: int64

In [298]:
num.iloc[2:6,[0]]

   n1
2   3
3   4
4   5
5   6

In [306]:
num.iloc[5,0].

6

**Step-13: how to append a row**

In [313]:
num.loc[9]=[10,100,1000]

In [317]:
len(num)

10

In [325]:
id=len(num)
num.loc[id]=[10,100,1000]

In [315]:
num

   n1   sq  cube
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16   464
4   5   25   125
5   6   36   216
6   7   49     0
7   8   64     0
8   9   81     0
9  10  100  1000

In [327]:
num

    n1   sq  cube
0    1    1     1
1    2    4     8
2    3    9    27
3    4   16   464
4    5   25   125
5    6   36   216
6    7   49     0
7    8   64     0
8    9   81     0
9   10  100  1000
10  10  100  1000

In [329]:
num.loc[len(num)]=[10,100,1000] # used for adding a row

In [331]:
num

    n1   sq  cube
0    1    1     1
1    2    4     8
2    3    9    27
3    4   16   464
4    5   25   125
5    6   36   216
6    7   49     0
7    8   64     0
8    9   81     0
9   10  100  1000
10  10  100  1000
11  10  100  1000

**Step 14: How to save dataframe**


- we can save dataframes in two ways 

- .csv

- .xlsx

- where i want to save : directory

- what the filename to save : filename

- what is the type of file : extension


- different folder : 'C:\Users\vinay\OneDrive\Documents\Study\stats\eda.csv'


- different folder : 'C:\Users\vinay\OneDrive\Documents\Study\stats\eda.xlsx'

-same folder : "data1.csv" or "data1.xlsx"


file handling

In [37]:
csv_path= r"C:\Users\vinay\OneDrive\Documents\Study\stats\eda.csv"
excel_path= r"C:\Users\vinay\OneDrive\Documents\Study\stats\eda.xlsx"
num.to_csv(csv_path)
num.to_excel(excel_path)

In [45]:
csv_path='eda.csv'
excel_path='eda.xlsx'
num.to_csv(csv_path)
num.to_excel(excel_path)

In [41]:
pd.read_csv(csv_path)

   Unnamed: 0  n1  sq  cube
0           0   1   1     1
1           1   2   4     8
2           2   3   9    27
3           3   4  16    64
4           4   5  25   125
5           5   6  36   216
6           6   7  49     0
7           7   8  64     0
8           8   9  81     0

In [43]:
pd.read_excel(excel_path)

   Unnamed: 0  n1  sq  cube
0           0   1   1     1
1           1   2   4     8
2           2   3   9    27
3           3   4  16    64
4           4   5  25   125
5           5   6  36   216
6           6   7  49     0
7           7   8  64     0
8           8   9  81     0

In [55]:
csv_path='eda.csv'
excel_path='eda.xlsx'
num.to_csv(csv_path, index=False) # index column created extra

num.to_excel(excel_path, index=False) # index column created extra

In [49]:
csv_path=r"eda.csv"
pd.read_csv(csv_path)

   n1  sq  cube
0   1   1     1
1   2   4     8
2   3   9    27
3   4  16    64
4   5  25   125
5   6  36   216
6   7  49     0
7   8  64     0
8   9  81     0

In [51]:
pd.read_csv(csv_path)

   n1  sq  cube
0   1   1     1
1   2   4     8
2   3   9    27
3   4  16    64
4   5  25   125
5   6  36   216
6   7  49     0
7   8  64     0
8   9  81     0

In [53]:
pd.read_excel(excel_path)

   n1  sq  cube
0   1   1     1
1   2   4     8
2   3   9    27
3   4  16    64
4   5  25   125
5   6  36   216
6   7  49     0
7   8  64     0
8   9  81     0

In [59]:
excel_path=r"C:\Users\vinay\OneDrive\Documents\Study\stats\eda.xlsx"
num.to_excel(excel_path)

In [61]:
excel_path=r'eda.xlsx'
pd.read_excel(excel_path)

   n1  sq  cube
0   1   1     1
1   2   4     8
2   3   9    27
3   4  16    64
4   5  25   125
5   6  36   216
6   7  49     0
7   8  64     0
8   9  81     0

In [63]:
pd.read_csv(csv_path)

   n1  sq  cube
0   1   1     1
1   2   4     8
2   3   9    27
3   4  16    64
4   5  25   125
5   6  36   216
6   7  49     0
7   8  64     0
8   9  81     0