In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import os

In [2]:
wine_df = pd.read_csv(r"C:\Users\vinay\Eda 2\winequality_red.csv")
visa_df = pd.read_csv(r"C:\Users\vinay\Downloads\Visadataset (1).csv")
path = r"C:\Users\vinay\Downloads\Visadataset (1).csv"

- Generally ML models are developed by maths

- Convert categorical column into Numerical column

- Here we transform data from categorical to numerical

- This method is known as **Encodding**

- Feature(column) analysis : First five sessions

- Feature Engineering: Transform the data

- Feature selection: Machine learning

- Before Model Developement

- We will do EDA: Exploratory data analysis

     - Features(columns) analysis:

       - categorical, numeriacal, Outlier analysis, Bivariate,
 
            Multivariate

        - we will get the insights
 
       

    
    - Feature Engineering:

        - we will modify the data
    
        - Models developed by maths
    
        - Encoding: convert categorical data to Numerical data
    
        - scaling: All the numerical column makes under one scale
    
        - Transformatiom: All the maths developed by assuming data follows normal distribution
    
        - convert skewed distribution to Normal

    - Feature selection:
 
        - Impute the outliers


        - ML needs data into numbers : Encoding
 
       
         - Scaling: Standardization and Normalization
 
         - Transformation: Convert non Normal distribution into Normal
 
              distribution

- map 

- LabelEncoder

- OneHotEncoder

In [6]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [7]:
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [8]:
# create a dict assisgn a num start with zero 
# for each labesl based on alphabetical oeder
d= {'Certified':0, 'Denied':1}

In [9]:
# map the dictionary with column 
visa_df['case_status']= visa_df['case_status'].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [10]:
visa_df = pd.read_csv(r"C:\Users\vinay\Downloads\Visadataset (1).csv")
visa_df['case_status'].unique()
d = {'Certified':0, 'Denied':1}
visa_df['case_status']= visa_df['case_status'].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [11]:
# visa_df = pd.read_csv(r"C:\Users\vinay\Downloads\Visadataset (1).csv")
visa_df['continent'].unique()
d1 = {'Asia':0, 'Africa':1, 'North America':2, 'Europe':3,
     'South America':4, 'Ocenia':5}
visa_df['continent'] = visa_df['continent'].map(d1)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0.0,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,0.0,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,0.0,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,0.0,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,1.0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0.0,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,0.0,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,0.0,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,0.0,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,0.0,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [12]:
visa_df = pd.read_csv(r"C:\Users\vinay\Downloads\Visadataset (1).csv")
labels = visa_df['continent'].unique()
d={}
for i in range(len(labels)):
    d[labels[i]] = i
d

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [13]:
visa_df = pd.read_csv(r"C:\Users\vinay\Downloads\Visadataset (1).csv")
labels = visa_df['continent'].unique()
d={}
for i in range(len(labels)):
    d[labels[i]] = i
d
visa_df['continent'] = visa_df['continent'].map(d)
visa_df['continent'].unique()

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [14]:
cat = visa_df.select_dtypes(include=object).columns
for i in cat:
    labels = visa_df[i].unique()
    # Dictionary Comprehension
    d = {labels[i]:i for i in range(len(labels))}
    
    visa_df[i] = visa_df[i].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,0,0,0,0,0,14513,2007,0,592.2029,0,0,0
1,1,0,1,1,0,2412,2002,1,83425.6500,1,0,1
2,2,0,2,0,1,44444,2008,0,122996.8600,1,0,0
3,3,0,2,0,0,98,1897,0,83434.0300,1,0,0
4,4,1,1,1,0,1082,2005,2,149907.3900,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,25475,0,2,1,1,2601,2008,2,77092.5700,1,0,1
25476,25476,0,0,1,0,3274,2006,1,279174.7900,1,0,1
25477,25477,0,1,1,0,1121,1910,2,146298.8500,1,1,1
25478,25478,0,1,1,1,1918,1887,0,86154.7700,1,0,1
25479,25479,0,2,1,0,3195,1960,3,70876.9100,1,0,1

In [15]:
# Dictionary Comprehension

# Label Encoder

- package name = **sklearn**

    - class: **preprocessing**

        - Method: **LabelEncoder**
****

     
- from sklearn.preprocessing import LabelEncoder

In [18]:
from sklearn.preprocessing import LabelEncoder

- Step-1: always import the method
- Step-3:  save th method
- step-3: Aplly fit transform

**fir transform**


   - fit: finding somthing

   - first we are finding dictionary

- transform: change the data

    - using dict we are changint Eng to number

In [20]:
from sklearn.preprocessing import LabelEncoder
# visa_df = pd.read_csv(r"C:\Users\vinay\Downloads\Visadataset (1).csv")
le  = LabelEncoder()
# le.fit_transform(visa_df['case_status'])
for i in cat:
    visa_df[i] = le.fit_transform(visa_df[i])

visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,0,0,0,0,0,14513,2007,0,592.2029,0,0,0
1,1,0,1,1,0,2412,2002,1,83425.6500,1,0,1
2,2,0,2,0,1,44444,2008,0,122996.8600,1,0,0
3,3,0,2,0,0,98,1897,0,83434.0300,1,0,0
4,4,1,1,1,0,1082,2005,2,149907.3900,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,25475,0,2,1,1,2601,2008,2,77092.5700,1,0,1
25476,25476,0,0,1,0,3274,2006,1,279174.7900,1,0,1
25477,25477,0,1,1,0,1121,1910,2,146298.8500,1,1,1
25478,25478,0,1,1,1,1918,1887,0,86154.7700,1,0,1
25479,25479,0,2,1,0,3195,1960,3,70876.9100,1,0,1

# **OneHotEncoder**

- The Method name is : pd.get_dummies


|case_status|case_staus_denied|case_staus_cerified|
|-|-|-|
|Denied|1|0|
|Certified|0|1|

In [22]:

visa_df= pd.read_csv(path)
pd.get_dummies(visa_df['continent'])

       Africa   Asia  Europe  North America  Oceania  South America
0       False   True   False          False    False          False
1       False   True   False          False    False          False
2       False   True   False          False    False          False
3       False   True   False          False    False          False
4        True  False   False          False    False          False
...       ...    ...     ...            ...      ...            ...
25475   False   True   False          False    False          False
25476   False   True   False          False    False          False
25477   False   True   False          False    False          False
25478   False   True   False          False    False          False
25479   False   True   False          False    False          False

[25480 rows x 6 columns]

In [23]:

visa_df= pd.read_csv(path)
pd.get_dummies(visa_df['continent'], dtype='int')

       Africa  Asia  Europe  North America  Oceania  South America
0           0     1       0              0        0              0
1           0     1       0              0        0              0
2           0     1       0              0        0              0
3           0     1       0              0        0              0
4           1     0       0              0        0              0
...       ...   ...     ...            ...      ...            ...
25475       0     1       0              0        0              0
25476       0     1       0              0        0              0
25477       0     1       0              0        0              0
25478       0     1       0              0        0              0
25479       0     1       0              0        0              0

[25480 rows x 6 columns]

In [24]:

visa_df= pd.read_csv(path)
pd.get_dummies(visa_df['case_status'])

       Certified  Denied
0          False    True
1           True   False
2          False    True
3          False    True
4           True   False
...          ...     ...
25475       True   False
25476       True   False
25477       True   False
25478       True   False
25479       True   False

[25480 rows x 2 columns]

In [77]:
visa_df= pd.read_csv(path)
for i in cat[1:]:
    a = pd.get_dummies(visa_df[i], dtype='int')
a

       Certified  Denied
0              0       1
1              1       0
2              0       1
3              0       1
4              1       0
...          ...     ...
25475          1       0
25476          1       0
25477          1       0
25478          1       0
25479          1       0

[25480 rows x 2 columns]

In [69]:
visa_df = pd.read_csv(path)
s = []

for i in cat[1:]:
    a = pd.get_dummies(visa_df[i], prefix=i, dtype='int')
    s.append(a)

# Merge all dummy DataFrames
final_dummies = pd.concat(s, axis=1)

print(final_dummies.head())

   education_of_employee_Bachelor's  education_of_employee_Doctorate  \
0                                 0                                0
1                                 0                                0
2                                 1                                0
3                                 1                                0
4                                 0                                0

   education_of_employee_High School  education_of_employee_Master's  \
0                                  1                               0
1                                  0                               1
2                                  0                               0
3                                  0                               0
4                                  0                               1

   has_job_experience_N  has_job_experience_Y  requires_job_training_N  \
0                     1                     0                        1
1                     0                     1                        1
2                     1                     0                        0
3                     1                     0                        1
4                     0                     1                        1

   requires_job_training_Y  region_of_employment_Island  \
0                        0                            0
1                        0                            0
2                        1                            0
3                        0                            0
4                        0                            0

   region_of_employment_Midwest  ...  region_of_employment_South  \
0                             0  ...                           0
1                             0  ...                           0
2                             0  ...                           0
3                             0  ...                           0
4                             0  ...                           1

   region_of_employment_West  unit_of_wage_Hour  unit_of_wage_Month  \
0                          1                  1                   0
1                          0                  0                   0
2                          1                  0                   0
3                          1                  0                   0
4                          0                  0                   0

   unit_of_wage_Week  unit_of_wage_Year  full_time_position_N  \
0                  0                  0                     0
1                  0                  1                     0
2                  0                  1                     0
3                  0                  1                     0
4                  0                  1                     0

   full_time_position_Y  case_status_Certified  case_status_Denied
0                     1                      0                   1
1                     1                      1                   0
2                     1                      0                   1
3                     1                      0                   1
4                     1                      1                   0

[5 rows x 21 columns]

In [83]:
visa_df = pd.read_csv(path)
dummies_list = []

for i in cat[1:]:
    a = pd.get_dummies(visa_df[i], prefix=i, dtype='int')
    dummies_list.append(a)

# Merge all into one DataFrame
all_dummies = pd.concat(dummies_list, axis=1)

print(type(all_dummies))   # ✅ <class 'pandas.core.frame.DataFrame'>
print(all_dummies.head())

<class 'pandas.core.frame.DataFrame'>
   education_of_employee_Bachelor's  education_of_employee_Doctorate  \
0                                 0                                0
1                                 0                                0
2                                 1                                0
3                                 1                                0
4                                 0                                0

   education_of_employee_High School  education_of_employee_Master's  \
0                                  1                               0
1                                  0                               1
2                                  0                               0
3                                  0                               0
4                                  0                               1

   has_job_experience_N  has_job_experience_Y  requires_job_training_N  \
0                     1                     0                        1
1                     0                     1                        1
2                     1                     0                        0
3                     1                     0                        1
4                     0                     1                        1

   requires_job_training_Y  region_of_employment_Island  \
0                        0                            0
1                        0                            0
2                        1                            0
3                        0                            0
4                        0                            0

   region_of_employment_Midwest  ...  region_of_employment_South  \
0                             0  ...                           0
1                             0  ...                           0
2                             0  ...                           0
3                             0  ...                           0
4                             0  ...                           1

   region_of_employment_West  unit_of_wage_Hour  unit_of_wage_Month  \
0                          1                  1                   0
1                          0                  0                   0
2                          1                  0                   0
3                          1                  0                   0
4                          0                  0                   0

   unit_of_wage_Week  unit_of_wage_Year  full_time_position_N  \
0                  0                  0                     0
1                  0                  1                     0
2                  0                  1                     0
3                  0                  1                     0
4                  0                  1                     0

   full_time_position_Y  case_status_Certified  case_status_Denied
0                     1                      0                   1
1                     1                      1                   0
2                     1                      0                   1
3                     1                      0                   1
4                     1                      1                   0

[5 rows x 21 columns]

In [40]:
visa_df = pd.read_csv(path)
path

'C:\\Users\\vinay\\Downloads\\Visadataset (1).csv'

In [61]:
visa_df = pd.read_csv(path)   # load once, outside loop

for i in cat:   # cat = list of categorical column names
    dummies = pd.get_dummies(visa_df[i], prefix=i)  # create dummies
    # visa_df = pd.concat([visa_df, dummies], axis=1) # add to dataframe

dummies

       case_status_Certified  case_status_Denied
0                      False                True
1                       True               False
2                      False                True
3                      False                True
4                       True               False
...                      ...                 ...
25475                   True               False
25476                   True               False
25477                   True               False
25478                   True               False
25479                   True               False

[25480 rows x 2 columns]

In [28]:

visa_df['continent'].values

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'], dtype=object)

In [52]:
import pandas as pd

data = {"Gender": ["M", "F", "M"],
        "Country": ["US", "IN", "US"]}
df1 = pd.DataFrame(data)

cat1 = ["Gender", "Country"]

for i in cat1:
    dummies = pd.get_dummies(df1[i], prefix=i)
    df1 = pd.concat([df1, dummies], axis=1)

print(df1)

  Gender Country  Gender_F  Gender_M  Country_IN  Country_US
0      M      US     False      True       False        True
1      F      IN      True     False        True       False
2      M      US     False      True       False        True

In [ ]:
visa_df.shape

In [ ]:
visa_df = pd.read_csv(path) 
num = visa_df.select_dtypes(exclude=object).columns
num

#**LABELENCODER VS ONEHOTENCODER**
- 

- Generally we dont want a relation ship between input columns

- we need both input columns are not correlated each other

- we need both input columns are **independent(XY)** of each other

- we need both input columns are **perpendicular** to each other

- we need both input columns are **orthogoanal** each other

- we need both input columns are **90 degree phase** shift each other

- OneHotEncoder will achive both

- But OneHotEncoder creates new columns

     - columns increase means dimensions increases

     - more dimensions data need more processing time

     - more dimension data need more infrastructure

     - This is called **curse of dimensionality**