In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [5]:
visa_df = pd.read_csv(r'Visadataset.csv')
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [25]:
data = {'Names':['Ramesh', 'Suresh', 'Satish', np.nan],
       'Age':[np.nan, 22, 25, 27],
       'City': ['Pune', 'Mum', np.nan, 'Hyd']}

df = pd.DataFrame(data)
df.to_csv('missing_nan.csv', index = False)
df

    Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0   Mum
2  Satish  25.0   NaN
3     NaN  27.0   Hyd

In [27]:
data = {'Names':['Ramesh', 'Suresh', 'Satish', None],
       'Age':[None, 22, 25, 27],
       'City': ['Pune', 'Mum', None, 'Hyd']}

df1 = pd.DataFrame(data)
df1.to_csv('missing_nan1.csv', index=False)
df1

    Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0   Mum
2  Satish  25.0  None
3    None  27.0   Hyd

In [29]:
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

In [31]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

In [33]:
df.isnull()

   Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [35]:
df1.isnull()

   Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [45]:
df.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [51]:
df.sum

<bound method DataFrame.sum of     Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0   Mum
2  Satish  25.0   NaN
3     NaN  27.0   Hyd>

# Method-1: fillna # not recomended

In [55]:
df.fillna(30)

    Names   Age  City
0  Ramesh  30.0  Pune
1  Suresh  22.0   Mum
2  Satish  25.0    30
3      30  27.0   Hyd

In [65]:
df['Age'].fillna(30) # series

0    30.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [67]:
df[['Age']].fillna(30) # dataframe

    Age
0  30.0
1  22.0
2  25.0
3  27.0

- In the above example we are filling values randmly 

- all the columns are filled with random numbers

- it is not a good approach beacause in data we have different data types

# What is the difference between np.nan and None

In [71]:
np.nan+5

nan

In [73]:
None+5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

- we should use np.nan in numerical column and None in categorical columns

In [77]:
arr1 = np.array([1,2, np.nan,3])
arr2 = np.array([1,2,None,3])

In [79]:
arr1

array([ 1.,  2., nan,  3.])

In [81]:
arr2

array([1, 2, None, 3], dtype=object)

In [83]:
np.nansum(arr1), np.sum(arr1)

(6.0, nan)

In [85]:
np.sum(arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [87]:
np.nansum(arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

- np.nan represents **float type**

- None represents **Object type**

- if data operations related to maths then nan format is better

- **Fill the value based on column**

In [97]:
#df.fillna()
df[['Names']].fillna('Manish')

    Names
0  Ramesh
1  Suresh
2  Satish
3  Manish

# Fill With Methods

- Whenever we are using methods no need to provide values

- pad

- bfill

- ffill

- backfill

In [139]:
data = {'Names':['Ramesh', 'Suresh', 'Satish', np.nan],
       'Age':[np.nan, 22, 25, 27],
       'City': ['Pune', 'Mum', np.nan, 'Pune']}

df = pd.DataFrame(data)
# df.to_csv('missing_nan.csv', index = False)
df

    Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0   Mum
2  Satish  25.0   NaN
3     NaN  27.0  Pune

In [157]:
df.fillna(method = 'pad') # replaces value by row

    Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0   Mum
2  Satish  25.0   Mum
3  Satish  27.0  Pune

In [159]:
import warnings
warnings.filterwarnings('ignore') # used to ignore warnings
df.fillna(method = 'pad') # replaces value by row

    Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0   Mum
2  Satish  25.0   Mum
3  Satish  27.0  Pune

In [113]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method = 'pad', axis=1)

    Names     Age  City
0  Ramesh  Ramesh  Pune
1  Suresh    22.0   Mum
2  Satish    25.0  25.0
3     NaN    27.0   Hyd

In [107]:
warnings.filterwarnings('ignore')
df.fillna(method = 'ffill')

    Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0   Mum
2  Satish  25.0   Mum
3  Satish  27.0   Hyd

In [105]:
warnings.filterwarnings('ignore')
df.fillna(method = 'bfill')

    Names   Age  City
0  Ramesh  22.0  Pune
1  Suresh  22.0   Mum
2  Satish  25.0   Hyd
3     NaN  27.0   Hyd

In [109]:
warnings.filterwarnings('ignore')
df.fillna(method = 'backfill')

    Names   Age  City
0  Ramesh  22.0  Pune
1  Suresh  22.0   Mum
2  Satish  25.0   Hyd
3     NaN  27.0   Hyd

In [111]:
df

    Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0   Mum
2  Satish  25.0   NaN
3     NaN  27.0   Hyd

# Mean - Median - Mode

- Mean >: use mean when there are not outliers data

- Median >: use median when there are outliers

In [117]:
age_mean = df['Age'].mean()
age_mean

24.666666666666668

In [121]:
df[['Age']].fillna(age_mean)

         Age
0  24.666667
1  22.000000
2  25.000000
3  27.000000

In [129]:
age_med = df['Age'].median()
df[['Age']].fillna(age_med)

    Age
0  25.0
1  22.0
2  25.0
3  27.0

In [145]:
mode = df['City'].mode()
mode # answer coming in series

0    Pune
Name: City, dtype: object

In [147]:
mode = df['City'].mode()
mode.values # we aplied .values so we get dataframe

array(['Pune'], dtype=object)

In [153]:
mode = df['City'].mode()
mode.values[0]

'Pune'

In [151]:
age_mod = df['City'].mode()
df[['City']].fillna(age_mod)

   City
0  Pune
1   Mum
2   NaN
3  Pune